### PR TITLE
Multiple updates to MobCannon.java

### PR DESCRIPTION
**Pull request by AdamQpzm**
Well I was bored so I thought I'd have a go at improving the repository. This is my second of two PRs I'm going to make for now - they don't really relate to each other, so I made two different ones :)

This PR is a lot more extensive than my previous PR. I've split it into multiple commits so that it's easier to explain and so that it's easier to change around if, for whatever reason, you prefer certain changes but don't want them all. All changes are to the MobCannon.java file. Explanation are as follows:

**Update new lines** - It's generally not conventional to have so many new lines. It's also not consistent with the other files in the project. There seems to be a new blank line after most, if not all, lines. I've removed a lot of the unnecessary blank lines, and have left some in to aid in readability. 

**Update the fields to be private and not needlessly static** - This is another simple one. Convention dictates the correct use of access modifiers. Since I didn't really see a reason any of the fields should be public (and certainly not public and non-final) I made them private. There was also a static field - static should only really be used when there's a good reason for it (and the main reason being immutable constants). Since a good reason for this wasn't clear, I removed it.

**Updated EntityType map in simple constructor** - The way the EntityType map was set up before was using the same HashSet for every EntityType. So far as I could tell, this was meant to represent mob aliases. Using the same Object for that doesn't really make sense - if at any point one tries to add a mob alias, then the alias will be applied to every EntityType (as it uses the same Object). I also altered the system to loop over an array of EntityTypes to reduce code duplication - this also makes it easier to add an EntityType at any point - simply add the EntityType to the array.

**Added null check for constructor** - It makes more sense to throw an IllegalArgumentException with a helpful message than to just include in the JavaDocs comment not to pass null values. At best, that approach would cause NPEs to be thrown and would be harder to debug for develoers. At worst, it could cause even more damage to other parts.

**Added null safety to eType** - Another NPE avoiding change. Before, it would throw an NPE when performing the equals() check if any of the values in the list were actually null - now it will simply ignore null values without throwing an exception.

**Updated blacklist logic** - No sense in checking the Map for disallowed values after adding them, when you could just not add them in the first place, eh?

**Updated style and logic** - The style was a little inconsistent - for example, sometimes missing the braces for single statement ifs, and sometimes not. I updated it to be more consistent. I also updated the logic to be a bit more logical - for example, there's no reason to check if the args length is greater than 0 in the else after checking if it's less than 1 - if wasn't less than 1, then it has to be greater than 0! If it was less than 1, the greater-than-0 statement would run (due to the else).

**Created Random field** - There's no real reason to create a new Random object every time. Doing so is wasteful, and apparently results in 'less random' results too.

**Removed potential infinite runtime** - There were a couple of things like this. For example, one place used a while loop to check whether someone had a permission. If they didn't, it'd take a random entity type and see if they had that permission, and so on until it found one the player did have permission for. This will freeze the server until it finds one they do have permission for - and since it's technically possible, however unlikely, that the same random number is generated lots of times, there's no upper limit on how long this operation can take. If they happen to have the random permission, but not permission for any of the mobs, this operation will definitely take forever. Oops!

So there are my suggestions. If you like them all, great! Feel free to pull. If you have concerns about any of the changes, don't hesitate to let me know and we can discuss them :)

### CODE REVIEW

**Comment by pookeythekid** [comment]
Just felt like saying, I figured I'd make usedNames static since it technically belongs to the class. There's no point in it changing in other instances. Anyway, good fixes.

**Comment by AdamQpzm** [comment]
@pookeythekid Fair enough, but the way you're using it isn't as if it should be static - the Map is changed by an instance method, so it seems like it should be an instance field. If this isn't the case, then the way it's used is probably wrong.

**Comment by JOSHSLAYDE** [comment]
Thanks for helping out the repository! You will be listed in the developers section when the plugin releases.

As per this repository just now being merged, sorry. I was out of state and didn't have time to process merge requests.

**Comment by JoshMullins** [comment]
Hey @AdamQpzm 
Where have ya been?

**Comment by AdamQpzm** [comment]
http://bukkit.org/threads/waves.336626/

Since this, I've not really paid any attention to any Bukkit related stuff :P

**Comment by JoshMullins** [comment]
Aw, sorry to see you leave.

**Pull request merged**
