### PR TITLE
Update README.md: Remove disguises

### PR DESCRIPTION
**Pull request by pookeythekid**
I don't believe we should have disguises in this plugin, since that would make it CB-version-dependent. It would probably be best that server owners simply go get a different disguise plugin and grant those permissions and such, so then they don't have to wait for this plugin (and LibDisguises [or whatever we'd be using]) to update if they want to update their servers.

### CODE REVIEW

**Comment by TGRHavoc** [comment]
@pookeythekid 
We could use packets that are sent to/from the client and the server to disguise the players, this would only require the server to have the correct version of ProtocolLib or our plugin (If we decided to implement out own packet managing system, although using an API like ProtocolLib would be much easier) for it to work.
Although, I do see the easier way of just getting the server owner to download a disguise plugin themselves but, I think that would defeat the purpose of using our gadget plugin unless we implement code to hook into each disguise plugin (which would be more work on us).

**Comment by JOSHSLAYDE** [comment]
I think it would be easier to use the API. Don't you?

**Comment by TGRHavoc** [comment]
@JOSHSLAYDE So, are we not having disguises, using an API for said disguises (Like DisguiseLib) or will we be implementing disguises using packets?

**Comment by pookeythekid** [comment]
<del>@TGRHavoc ProtocolLib requires being up to date with CraftBukkit, doesn't it? And it would be far easier on everyone to use API, as Josh said. About separate disguises, no one has to put on the plugin page that people should go get a separate disguise plugin; they've probably already done that in the first place.

<del>Anyway, gadgets at least a little different from disguises.</del>

As I was typing that I just realized that this could be solved with configuration options. The admin could choose to use MVPGadgets disguises or disable them and use another plugin instead. That way if other disguise plugins update their (technically-)one-task plugins while MVPGadgets is still updating all of its other features, users can switch from MVPGadgets to other disguises until MVPG is updated.

**Pull request merged**
